apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-lg3x
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0003-tenant/tkrw-pr712-0075-0003-app/devfile-sample-lg3x@sha256:bb6e637e5011bee7c3e994558331a67effcc02b4ada9a5905c477f7c3aae396f
        name: my-nodejs
        resources: {}
status: {}
